;=============================================================;
;                                                             ;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗    ;
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗   ;
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝   ;
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗   ;
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║   ;
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝   ;
;                                                             ;
;=============================================================;

[settings]
screenchange-reload = true
pseudo-transparency = true

include-directory = ~/.config/polybar/modules/

[colors]
background       = #1f1a17
background-alt   = #2c2520
foreground       = #f5f0e8
primary          = #ffbf00     
secondary        = #ffb347
alert            = #ff6b4a
disabled         = #6b6b6b    

[bar/main]
separator = |
separator-foreground = ${colors.secondary}

monitor = ${env:MONITOR:}
fixed-center = true
line-size = 0

border-top = 7pt
border-left = 14pt
border-right = 14pt
border-bottom = 0
width = 100%
height = 30pt


background = ${colors.background}
foreground = ${colors.foreground}


padding-right = 2
module-margin-left = 1
module-margin-right = 2

font-0 = JetBrainsMono Nerd Font:size14;3.5

modules-left = i3 xwindow
modules-center = date
modules-right = wireless-network pulseaudio battery power-menu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
wm-restack = i3
