#====================================================#
#                                                    #
#                picom.conf sample                   #
#                                                    #
#   To learn more about how to configure picom       #
#   go to https://picom.app/                         #
#                                                    #
#====================================================#

#################################
#             Shadows           #
#################################

shadow = true;
shadow-radius = 7; 
shadow-opacity = 1;
shadow-offset-x = 0;
shadow-offset-y = 0;

#################################
#           Fading              #
#################################

fading = true;
fade-in-step = 0.02;
fade-out-step = 0.02;

# Do not fade destroyed ARGB windows with WM frame. Workaround of bugs in Openbox, Fluxbox, etc.
# no-fading-destroyed-argb = false


#################################
#   Transparency / Opacity      #
#################################

# Range: 0.1 - 1.0
frame-opacity = 1;
inactive-dim-fixed = true;

#################################
#            Blur               #
#################################

# Parameters for background blurring, see BLUR section in the man page for more information.
blur-method = "dual_kawase";
blur-size = 15;
blur-strength = 10;

#################################
#       General Settings        #
#################################

backend = "glx";
dithered-present = true;
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;

# Use EWMH '_NET_ACTIVE_WINDOW' to determine currently focused window,
# rather than listening to 'FocusIn'/'FocusOut' event. May be more accurate,
# provided that the WM supports it.
# Default: false
# use-ewmh-active-win = false

detect-transient = true;
use-damage = true;

# WINDOW RULES 
rules: 
(
  {
    match = "class_g = 'kitty'";
    blur-background = true;
    opacity = 0.7;
  }, {
    match = "class_g = 'Code'";
    blur-background = true;
    opacity = 0.85;
  }, {
    match = "class_g = 'Polybar'";
    shadow = false;
  },{
    match = "class_g = 'i3'";
    blur-background = false;
    opacity = 1.0;
  }
)
