[module/date]
type = internal/date
interval = 1.0

; Formato principal (día de la semana, mes, día y hora)
date = %A, %B %d
time =%I:%M%p

; Formato al hacer click (más detallado)
date-alt = %A, %B %d, %Y
time-alt = %H:%M:%S

; Formato visual
format = 󰃭  <label>
format-background = ${colors.background-alt}
format-foreground = ${colors.foreground}
format-padding = 2

label = %date% - %time%
label-foreground = ${colors.foreground}

