[module/pulseaudio]
type = internal/pulseaudio

; ====================== VOLUMEN CON BARRA ======================
format-volume = <label-volume> <bar-volume>
format-volume-foreground = ${colors.foreground}
format-volume-padding = 1

label-volume = %percentage%%

; ====================== MUTEADO ======================
format-muted = <label-muted>
format-muted-foreground = ${colors.disabled}
format-muted-padding = 2

label-muted =   Muted

; ====================== CONFIGURACIÓN DE LA BARRA ======================
bar-volume-width = 10
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-indicator-foreground = ${colors.primary}

bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-fill-foreground = ${colors.primary}

bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = #555555

; ====================== ACCIONES DEL MOUSE ======================
click-right = com.saivert.pwvucontrol
click-middle = pavucontrol &

scroll-up = pulseaudio --increase
scroll-down = pulseaudio --decrease