[module/xwindow]
type = internal/xwindow

; Limita el título a 50 caracteres y agrega "..." si es más largo
label =   %instance:0:50:...%
label-empty = "  desktop"

; Estilo visual
format = <label>
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-padding = 1

; Si no hay ventana abierta, se ve más limpio
label-empty-foreground = ${colors.disabled}