[module/i3]
type = internal/i3
format = <label-state><label-mode>

; Focused (el que está activo)
label-focused = %index%
label-focused-background = ${colors.primary}
label-focused-foreground = #1f1a17
label-focused-padding = 2
 

; Unfocused normal
label-unfocused = %index%
label-unfocused-background = ${colors.background-alt}
label-unfocused-foreground = #aaaaaa
label-unfocused-padding = 2


; Visible (en otra salida)
label-visible = %index%
label-visible-background = ${colors.background-alt}
label-visible-foreground = ${colors.foreground}
label-visible-padding = 2

; Urgent
label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-foreground = #1f1a17
label-urgent-padding = 2

label-mode-padding = 2
label-mode-background = ${colors.alert}
label-mode-foreground = #1f1a17

label-separator = ""
label-separator-foreground = ${colors.disabled}

format-background = ${colors.background}
format-padding = 0
enable-scroll = false